---
title: Data Science for studying language and the mind
subtitle: Fall 2024
format:
    html: 
        toc: false
        number-sections: false
    pdf: default
---

::: {.callout-note title="Announcements"}

There are 3 options for those wishing to take the final exam: 

- Thursday, December 19, 2024: 12:00pm to 2:00pm in DRLB A8

If you can't make that official time, we can proctor 2 alternatives: 

- Tuesday, December 10 from 12:30pm to 2:30pm in the Linguistics Department 
- Thursday, December 12 from 12:30pm to 2:30pm in the Linguistics Department

Those with accommodations can request to take the exam with Weingarten any day between Dec 10th and Dec 19th. 

The final is in person, on paper, closed book/note/computer/phone, exactly like exams 1 and 2. The final will cover Sampling Distribution and Hypothesis testing from exam 1, and all of exam 2. 


:::

Welcome to Data Science for Studying Language & the Mind! The Fall 2024 course information and materials are below. Course materials from previous semesters are archived [here](archive.qmd).

{{< include _syllabus.qmd >}}

{{< include _resources.qmd >}}

{{< include _materials.qmd >}}

{{< include _schedule.qmd >}}

<!-- ## Lectures

Tuesdays and Thursdays from 12 - 1:29pm in TBD.

- **Week 1 (Aug 27) -- R Basics**: [Notes]() / [Slides]() / [Demo]() 
- Week 2 (Sep 3) -- Importing and tidying data: [Notes]() / [Slides]() / [Demo]() 
- Week 3 (Sep 10) -- Data visualization: [Notes]() / [Slides]() / [Demo]() 
- Week 4 (Sep 17)-- Sampling distribution: [Notes]() / [Slides]() / [Demo]() 
- Week 5 (Sep 24) -- Hypothesis testing: [Notes]() / [Slides]() / [Demo]() 
- Week 6 (Oct 1) -- Exam 1  
- Week 7 (Oct 8) -- Model specification 
- Week 8 (Oct 15) -- Model fitting
- Week 9 (Oct 22) -- Model accuracy 
- Week 10 (Oct 29) -- Model reliability 
- Week 11 (Nov 5) -- Classification 
- Week 12 (Nov 12) -- Exam 2
- Week 13 (Nov 19) -- Inference 
- Week 14 (Nov 26) -- Thanksgiving break (no class)
- Week 15 (Dec 3) -- Multilevel models
- Week 16 (Dec 10) -- Last day of class 
- Week 17 (TBD) -- Final exam (optional) -->





